### ISSUE TITLE
Upgrade to the released lit-element package

### ISSUE THREAD

**Issue by justinfagnani** [bolt-design-system/bolt#1162]
The `@polymer/lit-element` npm package has been moved to `lit-element`. `@polymer/lit-element` is deprecated and not receiving any updates, so please upgrade to `lit-element@^2.0.0` as soon as possible.

Thanks!

**Comment by sghoweri** [comment]
We've added this to our backlog to take care of ASAP (nothing in production is using this old version of `@polymer/lit-element` thankfully -- just `lit-html`) -- thanks @justinfagnani!

**Comment by sghoweri** [comment]
Should be all set @justinfagnani! Closing this on out 👍🏼

PS. Loved your SFHTML meetup talk you just gave (watched it on YouTube)!
