### ISSUE TITLE
Error: no such file or directory ./bolt/packages/build-tools/node_modules/find-up

### ISSUE THREAD

**Issue by mralexho** [bolt-design-system/bolt#1176]
Hello! I just watched your DrupalCon Seattle presentation and wanted to checkout the design system. I immediately ran into install issues and didn't find a related ticket.

1. Please briefly describe the issue being encountered.
	* `npm run setup` returns error

2. Which components / demos / component examples / variations is this issue affecting? 
	* Install step

3. Which browsers / browser versions / devices / OSs are having this particular issue?
	* macOS Mojave 10.14.3

4. Which branch(es) are seeing this issue?
	* master

5. Is this a regression? If so:
	* I don't think so

6. When applicable, please provide a screenshot showing the behavior working as expected vs the currently broken behavior being observed.

[
![carbon](https://user-images.githubusercontent.com/704457/57876754-21831b80-77e4-11e9-8c24-f02349e86984.png)
](url)

**Comment by margoromo** [comment]
Thanks @mralexho for reaching out! We are taking a look at this and can get back to you shortly.

-Margo
Bolt Design System Product Owner

**Comment by sghoweri** [comment]
Hey thanks @mralexho! 

We've been running into this same error on our end as well (we already had a ticket on our internal board to debug this). We're still not quite sure why this is happening (possibly an issue with an upstream dependency) however in our experience, re-running `yarn` a 2nd time almost always seems to do the trick!

(also just in case it pops up for ya, there's also been [this particular](https://github.com/lovell/sharp/issues/1593) Sharp error more recently popping up when the images task is first booting up. Same workaround applies (re-running the build tools) but this has been a more finicky bug to squash!)

**Comment by mralexho** [comment]
Thanks for the quick response!

@sghoweri you were correct, running the command a 2nd time fixes the issue (not sure why I didn't just try that before). Thanks for the heads up with sharp builds 🤞

**Comment by mralexho** [comment]
I just ran the next command `npm start` (twice this time) and received the following -

![carbon](https://user-images.githubusercontent.com/704457/57886354-01ab2200-77fb-11e9-9333-b643b2ccbfe3.png)

Let me know if you need any additional debug logs. And thanks for helping!

**Comment by mralexho** [comment]
Sorry I'm not too sure how to handle. I applied  
@nstuyvesant's https://github.com/lovell/sharp/issues/1593#issuecomment-475680243 steps for installing vips and sharp but now I'm getting these errors -

![carbon (1)](https://user-images.githubusercontent.com/704457/57933503-79c12880-788b-11e9-9993-104b54122dbe.png)

**Comment by sghoweri** [comment]
@mralexho ugh, so sorry for the rough onboarding! 

Since `@bolt/build-tools` should be requiring `address`, I’m wondering if your version of yarn could be out of date or if the Sharp Mac OS workaround could have thrown something off with the install of the monorepo dependencies 🤔

Out of curiosity, could you try running `npm run clean` to wipe any local NPM / Composer dependencies, then try running `npm run setup` and `npm start` to see if that missing package gets correctly installed?

**Comment by mralexho** [comment]
Hi @sghoweri, no apologies necessary at all! I'm sure you have many other things to do than debug issues.

I upgraded to yarn v1.16.0 and ran `npm run clean` and `npm run setup` but still have some dependency errors -

![carbon](https://user-images.githubusercontent.com/704457/58283831-57417a80-7d77-11e9-91bf-7582e5f2cb6d.png)

It looks like the same original error with the find-up module?

**Comment by mralexho** [comment]
@sghoweri @margoromo just pulled the latest codebase and it's running now!

Can't wait to test this out with my team. Thanks! 😸
