### ISSUE TITLE
Disabling JS affects the HTML syntax display on code-snippet syntax demo page

### ISSUE THREAD

**Issue by TashaBasalt** [bolt-design-system/bolt#1214]
# Bolt Docs: Developer Filing an Issue

1. When testing the demo page for code snippets, by turning off the Javascript, I noticed that the HTML block seemed to render the code instead of displaying the tags.
2. Which components / demos / component examples / variations is this issue affecting? 
	The Code-Snippet Component
3. Which browsers / browser versions / devices / OSs are having this particular issue?
         Chrome Browser

4. Which branch(es) are seeing this issue?
         feature/code-snippets
	
To put this another way — is this issue *visibly broken* **everywhere** this component is used? Or does it work fine in some places?
         The HTML blocks are visibly broken anywhere used while JS is disabled.

5. Is this a regression? If so:
          Not that I know of.

6. When applicable, please provide a screenshot showing the behavior working as expected vs the currently broken behavior being observed.
<img width="1680" alt="Screen Shot 2019-06-18 at 11 35 51 AM" src="https://user-images.githubusercontent.com/51337290/59712734-a33ede00-91c2-11e9-987a-157d5beb4bbb.png">
<img width="984" alt="Screen Shot 2019-06-18 at 12 13 34 PM" src="https://user-images.githubusercontent.com/51337290/59712735-a33ede00-91c2-11e9-8a69-25491f683a32.png">

**Comment by margoromo** [comment]
Hey @adamszalapski can you please check this out?

**Comment by adamszalapski** [comment]
Hi @TashaBasalt sorry for that long delay. Today i create separate PR https://github.com/bolt-design-system/bolt/pull/1224 covering this issue. Twig version of code-snippet is not 100% the same as JS version but is similar. Please let me know if you have more questions. You can check my PR as well and i will more than happy for some feedback.
