### ISSUE TITLE
object-inline-list - text wraps, items don't

### ISSUE THREAD

**Issue by charginghawk** [bolt-design-system/bolt#133]
Right now, with the inline list objects, the items aren't wrapping, but the text within them are:

<img width="321" alt="screen shot 2017-09-25 at 1 14 03 pm" src="https://user-images.githubusercontent.com/7936651/30821977-493eeee0-a1f5-11e7-9498-652fc682c19e.png">

This is in contrast with the Pegakit inline list (as seen in the current pega.com footer), where the text doesn't wrap but the items do:

<img width="278" alt="screen shot 2017-09-25 at 1 14 17 pm" src="https://user-images.githubusercontent.com/7936651/30821976-493dc100-a1f5-11e7-9ce2-a640ff1e61d6.png">

**Comment by charginghawk** [comment]
The updates resolved this.

**Comment by sghoweri** [comment]
👍
