### ISSUE TITLE
object-ui-list - need size options (o-bolt-ui-list--small)

### ISSUE THREAD

**Issue by charginghawk** [bolt-design-system/bolt#136]
Similar to issue #132, but for ui lists. The default spacing is too large with no options.

![screen shot 2017-09-25 at 3 53 27 pm](https://user-images.githubusercontent.com/7936651/30934620-262e6374-a39c-11e7-95a4-b6a0fa7cb97c.png)

**Comment by sghoweri** [comment]
Fixed with #147!
