### ISSUE TITLE
Unsanitized buttons

### ISSUE THREAD

**Issue by charginghawk** [bolt-design-system/bolt#149]
In Pegakit, we used the sanitize.css library in our generics to set a clean default for buttons. Since we don't use that library in Bolt, our buttons aren't looking so clean out of the box.

Before:
![screen shot 2017-10-10 at 1 10 29 pm](https://user-images.githubusercontent.com/7936651/31400242-e0af3f32-adbc-11e7-8ce1-28627e1e006d.png)
![screen shot 2017-10-10 at 1 10 45 pm](https://user-images.githubusercontent.com/7936651/31400245-e3bd72c0-adbc-11e7-9c8b-047784a28992.png)

After:
![screen shot 2017-10-10 at 1 10 25 pm](https://user-images.githubusercontent.com/7936651/31400252-ea964748-adbc-11e7-88e3-6972d761e04c.png)

**Comment by mikemai2awesome** [comment]
Is this built with `c-bolt-button`? The clean reset is currently applied to the button component. @charginghawk

**Comment by charginghawk** [comment]
@mikemai2awesome Niet, it's based off the markup @sghoweri used for the Academy search form adapted to pega.com's new nav. So, for example:

```<button class="c-global-search__submit" type="submit">
    <span class="u-visuallyhidden">Search Pegasystems</span>
    <svg class="c-global-search__search-icon o-icon" viewBox="0 0 24 24">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#search"></use>
    </svg>
</button>```

**Comment by sghoweri** [comment]
stale issue from a year ago for Bolt v0.x. closing out since this should have already been addressed a while ago but please re-open if this is still indeed an issue.
