### ISSUE TITLE
Allow Drupal to compile non-minified for debugging on the Drupal end

### ISSUE THREAD

**Issue by remydenton** [bolt-design-system/bolt#247]
Use case: https://github.com/bolt-design-system/bolt/pull/244

**Comment by sghoweri** [comment]
@remydenton I don't disagree at all with the end goal of this however I very strongly suggest we flip it ever so slightly: "Allow **Drupal** to compile non-minified Bolt js for debugging on the Drupal end".

The exact same reasons why Drupal needs to be able to compile Sass on its own apply to JavaScript all the same (if not more so): better flexibility, better extensibility (ie. extend base JS components and adapt as needed), better web performance, more control on how things get bundled together and delivered, etc.

See my last PR #250 for an example of how we set this up using literally the current build process we already have in place. The only change I think we should make outside of the larger 1.x epic is perhaps contidionally disable Uglification if the environmental variable is set to `development`

**Comment by remydenton** [comment]
Title updated :).  This issue will basically be a non-issue once we get Drupal set up to do the compiling on its own.  Awesome!

**Comment by charginghawk** [comment]
Minification is currently causing more problems than it's solving, and honestly I don't expect that to change until we're out of beta/alpha. At the very least there should be unminified versions of the released javascript in dist. Otherwise this is just an instance of premature optimization being the root of all evil.
