### ISSUE TITLE
Speed up initial set up

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#305]
We want to increase how quickly a new developer can clone the repo, run installs, and get setup to work. This needs to be fast & consistent.

- Yarn instead of npm
- Yarn Workspaces
- Less packages for Lerna to link  
- Clean out, remove unused or unnecessary npm dependencies

**Comment by sghoweri** [comment]
Closing out since all 4 of the goals of this should be all set based on latest architecture
