### ISSUE TITLE
v1.0 Overview

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#306]
# Here we go! 🎉 

The purpose of this specific issue is to summarize the *why* behind *what* we're doing as we march towards a 1.0 release of Bolt. I'd like to give a high level overview of the goals and to summarize the different initiatives that make it up. If you're curious about the specific issues that make this all up, see these links:

- All issues attached to the [v1.0 milestone](https://github.com/bolt-design-system/bolt/milestone/7)
- Those issues on a [kanban board](https://github.com/bolt-design-system/bolt/projects/3)

Working with Bolt can be a bit daunting for those new to design systems. Gaining a comprehensive understanding of the complete system is time consuming and can carry a steep learning curve. In order to help make it easier to learn and quicker to implement, we’re actively pushing Bolt in a direction that does not require a comprehensive understanding to use and get value from. 

The goal of this is to broaden adoption across the organization. In order to accomplish this, we will focus on improving the experience of two the main types of users – those that create elements of the Design System and those that utilize and consume the Design System in other environments such as the Drupal sites that Pega maintains.

### Improve the experience exploring and adopting Bolt 

* Create tools, documentation and resources to ease the adoption by Drupal developers.
* Improve the Bolt Design website experience to all for better usability and exploration of components.

### Improve the component creation experience 

* Develop tooling that assists in creating components quickly and correctly using defined best practices
* Ensuring components are created in a way that can be consumed in a different environment (like Drupal) without the creator having to be aware of the nuances required.
* Improve how quickly someone can get started on the overall system by increasing initial start up speed and reducing common technical barriers.
* Improve how quickly frequent day-to-day tasks take such as build speeds.

## Initiatives 

In order to accomplish the above goals, we'll focus on these features & initiaves:

### Restructuring code base to clarify templating purpose

Currently templates in Bolt serve an ambiguous purpose that could be either to provide a reusable component that is intended to be implemented in other environments such as Drupal, or to simply demonstrate how that component could be used in many different ways. The distinction is crucial to get right if the components are to be used flexibly across Pega sites. 

### Implement JSON schema definitions for components

[JSON Schemas](https://spacetelescope.github.io/understanding-json-schema/) define data structure clearly, and this will allow the components to clearly state what data they need and how it should look. This will help prevent mysterious errors and confusing implementations while providing other tangible and exciting benefits, such as:

* Automatically generated documentation for all components.
* Providing tests when the components are used in Drupal to determine potential points of failure earlier and easier - helping to save time and ease frustration.
* Providing component creators with effecient methods of showcasing component variations.

### Create documentation catered towards Drupal developers consuming & implementing Bolt

The restructuring of code will help with this, as will the JSON schemas, but we'll also need to improve the tooling so they can easily compile and implement Bolt correctly without having to understand the deep specifics. We'll create some examples and resources to help as well.

### Addressing general technical debt

This is a good opportunity to do some neglected cleanup and fine tuning. Not only is it something that needs to be done, but it will help the consumers and creators focus on what they're trying to do instead of having to wrap their heads around legacy approaches.

**Comment by danigrrl** [comment]
This is great! Thanks for the update, Evan. I think we can be even more concise in future releases, but this is very similar to the design briefs we use. I'll add this to our Confluence space.
