### ISSUE TITLE
Implement JSON Schema for the Blockquote component

### ISSUE THREAD

**Issue by sghoweri** [bolt-design-system/bolt#307]
Part of the Epic v1 JSON Schema buildout: https://github.com/bolt-design-system/bolt/issues/302

Blockquote component for reference:   https://github.com/bolt-design-system/bolt/tree/release/0.x/src/_patterns/02-components/bolt-blockquote

A couple things to consider:
- Is every exposed option reflected here?
- Are there certain combinations of options that are opinionated? Ex. the border positioning based on the overall blockquote alignment?
- How can we consolidate, normalize, and share the definitions and options of different config params (ex. text alignment here vs in the headline component -- aren't these the same thing?)
- Is the Twig template validation duplicating (or even conflicting) validation getting handled by the JSON Schema? If so, how do we handle this **systematically**? (and no, manually trying really hard to keep these from getting tangled up isn't going to cut it)

**Comment by remydenton** [comment]
@sghoweri, how does this relate to #302?  Were you thinking to create separate tasks for the documentation of each component?

**Comment by sghoweri** [comment]
@remydenton this is just spelling out some of the sub-tasks involved in the larger epic so we can start biting off manageable chunks of work
