### ISSUE TITLE
Create Example Drupal Theme

### ISSUE THREAD

**Issue by sghoweri** [bolt-design-system/bolt#357]
Integration in apps similar to Pattern Lab, taking advantage of new build tools CLI

**Comment by sghoweri** [comment]
Basic Drupal Lab theme in place with several additional updates about to ship:
https://github.com/bolt-design-system/bolt/tree/master/example-integrations/drupal-lab/web/themes/flash

Closing out.

**Comment by TipiT** [comment]
> Basic Drupal Lab theme in place with several additional updates about to ship:
> https://github.com/bolt-design-system/bolt/tree/master/example-integrations/drupal-lab/web/themes/flash
> 
> Closing out.

I think you should take the /flash away so the link finds the theme. :)

**Comment by sghoweri** [comment]
👍🏼

**Comment by TipiT** [comment]
Is there a plan for a official Drupal theme release to drupal.org?
