### ISSUE TITLE
Bolt CLI - Out of Memory Error

### ISSUE THREAD

**Issue by sghoweri** [bolt-design-system/bolt#370]
I kind of shrugged it off the first time this happened but now that this has happened to me a second time I figure to bring this up as a potential memory leak red flag.

For reference, this was just via the default `npm run start` npm task using the most recently CLI work we've done (ie. normal Webpack + PL watch with verbosity turned town) - no new changes or modifications on my local build or tooling.

<img width="1440" alt="bolt_cli_-_out_of_memory_error" src="https://user-images.githubusercontent.com/1617209/35197626-f0353b0c-feaf-11e7-8290-41d24f358fd9.png">

Granted, this error was thrown after having my one watch task running in the background for a hair under 5 hours so I'm not as concerned about this _just_ yet however I'm thinking that with the addition of more parallel tasks this could likely be a much bigger issue in the near future...

@EvanLovely any thoughts on this?

**Comment by EvanLovely** [comment]
Yeah, this is important to fix. Have any idea on how I can reproduce besides use it for 5 hours?

**Comment by sghoweri** [comment]
@EvanLovely unfortunately this seems to be getting worse. >_<

 I'm seeing the latest Bolt CLI throwing memory errors between 20 minutes to an hour after doing some component-specific JavaScript work (3 stack traces attached from just today). 

Have you guys seen anything like this when doing any JavaScript-specific work in Bolt to make Webpack work a little? We should totally chat about this tomorrow - might have a couple ideas to help troubleshoot this.

[stack-trace-3.txt](https://github.com/bolt-design-system/bolt/files/1693512/stack-trace-3.txt)
[stack-trace-2.txt](https://github.com/bolt-design-system/bolt/files/1693513/stack-trace-2.txt)
[stack-trace-1.txt](https://github.com/bolt-design-system/bolt/files/1693514/stack-trace-1.txt)

CC @joekarasek @rockymountainhigh1943 @theSadowski

**Comment by EvanLovely** [comment]
Down to chat more soon; have my eyes on either diconnected long running child processes or storing output in vars (and then optionally displaying them based on verbosity) instead of streaming output. 

Most of my work has been on the internals, so not starting & stopping often. Any sight of this @joekarasek @rockymountainhigh1943 ?

**Comment by rockymountainhigh1943** [comment]
I haven't noticed this happen yet or I've been so heads down I just restarted the task quickly while moving along. I'll keep an eye out for it and note any specific task that triggers the event.

**Comment by sghoweri** [comment]
Closing this one out. Haven’t encountered this issue for a while... will re-open if this ends up coming back.
