### ISSUE TITLE
IE performance issue

### ISSUE THREAD

**Issue by theSadowski** [bolt-design-system/bolt#377]
Links to: http://vjira2:8080/browse/BK-159

We have been working on resolving a specific issue, considered a release-blocker for product pages: Smooth scrolling/Sticky performance issue in IE (http://vjira2:8080/browse/WWWD-1105).
Thomas spent a good amount to time today tweaking the smooth scrolling and Rémy spent some time on the gumshoe behavior in IE 11. The page we have been looking at is https://demo1.d8.pega.com/uat-t2-test. It is ready for review, so we checked it out. The specific complaint on the ticket is somewhat improved.
 
When reviewing the results this evening we started looking at the overall, macro performance of the page in IE 11 – and it’s scary.
* What we are seeing seems to be that page scrolling cannot happen at all until all the images are loaded. Try loading that page, or other of the demo pages (an image-lighter page would be, e.g., https://demo1.d8.pega.com/crm-t1) in IE 11 / Win 7. The side scrollbar is literally locked in place for approximately 10 seconds, until all images are loaded.
* Images are loading extremely slowly, about a second per large image.
* Another observed behavior is that the images don’t seem to be caching. There is almost no speed increase from having loaded the page previously.
* Another behavior is that on longer-running (image-heavy) pages, IE is throwing up a dialog saying that the page is unresponsive due to a long-running script, with the option to disable JavaScript, or sometimes “Recover pega.com”. This usually disappears when the script completes, but clearly this should not be happening.
 
I suspect that this has to do with a compound of issues – IE 11 scripts running 20 times slower than modern browsers, more shims loaded, etc. Thinking this might be a Drupal-specific issue, we found a page on Bolt which displays the exact same behavior. So, it seems to be in Bolt.  See https://bolt.netlify.com/patterns/04-pages-d8-product-landing-d8-product-t2/04-pages-d8-product-landing-d8-product-t2.html in IE 11.
 
We are seeing traces of this behavior on the current production homepage. We missed this in the past because there are few images on the home page, but now that we are looking for it, the evidence (locked scrollbar while images load) is apparent. There are currently no other complex pages on prod to compare to.
 
Additional clarity: all the details in the issue description are in support of a single bug, not multiple issues. I do not know the root cause, for sure, so I wanted to include as much detail as possible. Please take it as a whole. 
The bug is: IE 11/image performance issues (specifically, the screen locking while image are loading).

**Comment by sghoweri** [comment]
old issue with many many updates added since to help improve IE 11 performance. issues mentioned here haven’t been reported recently so closing this out.
