### ISSUE TITLE
Bolt site links look like plain text

### ISSUE THREAD

**Issue by EvanLovely** [bolt-design-system/bolt#680]
<img width="1193" alt="screenshot_2018-05-04_02-03-58_pm" src="https://user-images.githubusercontent.com/569699/39653024-3f65a028-4fa4-11e8-9816-698c823f2ac3.png">

**Comment by EvanLovely** [comment]
I would suggest the quickest solution to implement that would be the easiest to remove later:

1. In just the Bolt Site, add a parent selector in **one** of these places:
    - `<body>`
        - Add a class like `<body class="isBoltSite">` **OR** 
        - Perhaps base it off the `env` from `.boltrc.js`: `<body bolt-env="static">`
    - The tag that wraps generated markdown: `<div class="is-markdown">`
2. In the styles that are only for the Bolt Site, add the styles the anchor links if they are under an above tag, like `.is-markdown a`. 

I think using a tag that wraps generated markdown and is just a style for the Bolt Site is the way to go, so then we don't need to worry about sending new styles to Drupal.

**Comment by sghoweri** [comment]
closing out - no longer an issue
